language: python
os:
  - linux
  - osx
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install poetry coveralls
  - poetry install
script:
  - pytest --cov=dialogy
after_success:
  - coveralls
